// <auto-generated/>
#pragma warning disable CS0618
using Bund.API.Autobahn.Client.Details.Electric_charging_station.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bund.API.Autobahn.Client.Details.Electric_charging_station
{
    /// <summary>
    /// Builds and executes requests for operations under \details\electric_charging_station
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class Electric_charging_stationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bund.API.Autobahn.Client.details.electric_charging_station.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bund.API.Autobahn.Client.Details.Electric_charging_station.Item.WithStationItemRequestBuilder"/></returns>
        public global::Bund.API.Autobahn.Client.Details.Electric_charging_station.Item.WithStationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("stationId", position);
                return new global::Bund.API.Autobahn.Client.Details.Electric_charging_station.Item.WithStationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bund.API.Autobahn.Client.Details.Electric_charging_station.Electric_charging_stationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Electric_charging_stationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/details/electric_charging_station", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bund.API.Autobahn.Client.Details.Electric_charging_station.Electric_charging_stationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Electric_charging_stationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/details/electric_charging_station", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
