// <auto-generated/>
#pragma warning disable CS0618
using Bund.API.Autobahn.Client.Item.Services;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bund.API.Autobahn.Client.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \{roadId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class WithRoadItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The services property</summary>
        public global::Bund.API.Autobahn.Client.Item.Services.ServicesRequestBuilder Services
        {
            get => new global::Bund.API.Autobahn.Client.Item.Services.ServicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bund.API.Autobahn.Client.Item.WithRoadItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRoadItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{roadId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bund.API.Autobahn.Client.Item.WithRoadItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRoadItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{roadId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
