// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bund.API.Autobahn.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum DisplayType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ROADWORKS")]
        #pragma warning disable CS1591
        ROADWORKS,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBCAM")]
        #pragma warning disable CS1591
        WEBCAM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARKING")]
        #pragma warning disable CS1591
        PARKING,
        #pragma warning restore CS1591
        [EnumMember(Value = "WARNING")]
        #pragma warning disable CS1591
        WARNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEIGHT_LIMIT_35")]
        #pragma warning disable CS1591
        WEIGHT_LIMIT_35,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOSURE")]
        #pragma warning disable CS1591
        CLOSURE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOSURE_ENTRY_EXIT")]
        #pragma warning disable CS1591
        CLOSURE_ENTRY_EXIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "STRONG_ELECTRIC_CHARGING_STATION")]
        #pragma warning disable CS1591
        STRONG_ELECTRIC_CHARGING_STATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHORT_TERM_ROADWORKS")]
        #pragma warning disable CS1591
        SHORT_TERM_ROADWORKS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ELECTRIC_CHARGING_STATION")]
        #pragma warning disable CS1591
        ELECTRIC_CHARGING_STATION,
        #pragma warning restore CS1591
    }
}
